steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Pragati670/repo5.git']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']
#kubectl set image deploymentname deployment/deployment-2 myapp-sha256-1 (container name old one)
  - name : 'gcr.io/cloud-builders/kubectl'
    args: 
    - 'set'
    - 'image'
    - 'deployment/deployment-2'
    - 'myapp-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
    env :
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-clusternew'
 
substitutions:
  _PROJECT_ID: gcp-devops-455806
  _CINAME: gke-image
  _VERSION: v2.0

options:
  logging: CLOUD_LOGGING_ONLY

